config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :listings
  resources :people 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many_attached :images
end

app/models/person.rb
class Person < ApplicationRecord

  has_many :addresses

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save 
      flash[:notice] = "Listing successfully created"
      redirect_to listing_path @listing
    else
      flash[:alert] = "Error: #{ @listing.errors.full_messages }"
      render :new
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end  

  private
  def listing_params
    params.require(:listing).permit(:address, :unit, :bedrooms, :bathrooms, :sqft, images: [])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tenate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <div class="page-main">
        <div class="relative">
          <div class="relative z-20 shadow">
            <div class="mx-3 overflow-visible flex flex-col flow-root justify-between items-center px-4 py-5 sm:px-6 sm:py-4 md:justify-start">
              <div class="flex flex-grow">
                <div class="flex items-center mr-6">Tenate</div>
                <div class="hidden md:flex-1 md:flex md:items-center md:justify-between mx-3">
                  <nav class="flex space-x-10">
                    <%= link_to 'Home', listings_path %>
                    <%= link_to 'Create listing', new_listing_path %></nav>
                  </nav>
                  <div class="flex items-center md:ml-12"><%= link_to 'Sign in', new_user_session_path %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class="min-h-screen flex flex-col py-12 sm:px-6 lg:px-8">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/listings/index.html.erb
<ul class="list-none">
<% @listings.each do |listing| %>
  <li><%= link_to listing.address, listing_path(listing) %></li>
<% end %>
</ul>

app/views/listings/new.html.erb
<div class="sm:mx-auto sm:w-full sm:max-w-md">
  <h1 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Create a new listing</h1>
  <%= form_with model: @listing do |form| %>
    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
      <div class="sm:col-span-6 grid">
        <%= form.label :address, class: "text-sm font-medium text-gray-700" %> 
        <%= form.text_field :address, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 w-96 sm:text-sm border-gray-300 rounded-md" %>
      </div>
      <div class="sm:col-span-6">
        <%= form.label :unit, class: "text-sm font-medium block text-gray-700" %>
        <%= form.text_field :unit, max_length: 4, class: "block shadow-sm focus:ring-indigo-500 focus:border-indigo-500 w-24 sm:text-sm border-gray-300 rounded-md" %>
      </div>
      <div class="sm:col-span-3">
        <%= form.label :bedrooms, class: "block text-sm font-medium text-gray-700" %>
        <%= form.select :bedrooms, 0..5, {}, class: "mt-1 block w-24 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" %>
      </div>
      <div class="sm:col-span-3">
        <%= form.label :bathrooms, class: "block text-sm font-medium text-gray-700" %>
        <%= form.select :bathrooms, 1..5, {}, class: "mt-1 block w-24 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" %>
      </div>
      <div class="sm:col-span-3">
        <%= form.label :sqft, 'Square feet:', class: "block text-sm font-medium text-gray-700" %>
        <%= form.number_field :sqft, in: { min: 100, max: 100000 }, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-24 sm:text-sm border-gray-300 rounded-md" %>
      </div>
      <div class="sm:col-span-3">
        <%= form.label :images, 'Upload photos', class: "block text-sm font-medium text-gray-700" %>
        <%= form.file_field :images, multiple: true, direct_upload: true, class: "" %>
      </div>
      <div class="my-4"><%= form.submit 'Add listing', class: "inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %></div>
    </div>
  <% end %> 
</div>

app/views/listings/show.html.erb
<ul class="list-none">
  <li>Address: <%= @listing.address %></li>
  <li>Unit: <%= @listing.unit %></li>
  <li>Bedrooms: <%= @listing.bedrooms %></li>
  <li>Bathrooms: <%= @listing.bathrooms %></li>
  <li>Size: <%= @listing.sqft %> ft<sup>2</sup></li>
  <%= image_tag url_for(@listing.images.first), size: "450x300" if @listing.images.attached? %>
</ul>

<div>
  <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
  <div class="mt-1">
    <input type="text" name="email" id="email" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" placeholder="you@example.com" aria-describedby="email-description">
  </div>
  <p class="mt-2 text-sm text-gray-500" id="email-description">We'll only use this for spam.</p>
</div>

app/views/people/index.html.erb
<h1>People List</h1>
<% @people.each do |person| %>
  <%= link_to(person.first_name + ' ' + person.last_name, person_path(person)) %>
<% end %>

app/views/people/show.html.erb
<%= @person.first_name %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>